---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-admin-creds
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-password: AgAwhNnHW7g4F7fKXBBiKGjzVbzVpYdl/BARvkX0glZ78VFB173Y/lz1g3/yPhTsWG9BXZJPK8dscNcCoWdmJP7qOpLy4YHQzZNeb9Hf3J2wNfpDSTJZdwk57P1O56VEZev1OY0SrB2v+lvp1cZClpu3YiHQ75KfZD4GXB1i7G84l4smRjnXrVtiwzDDM1FGqShiwNfe/SPNZu0sTdM3b3rC4Kk7/kfCPJNpi05/xguENsfyCeC5oAjYksIhtbruISiMTcFzuJyDPk+AHEG2qnd28YQ5wjjAaf+FX8Ei9hD7FV7GatX7mgwfSVuFUICv2o49gtdaQ6axn+w5/2vFTkAIEqD3IJPkHsZALaVJx1nb3JcDb7EsAltHX81InPAEd5cxbyMblNaDrInsmuAvV0+s1xF5DDmi73HcfgkvYE+KK/hhdnAPEmkYA6vISd87OoCu9RrJcfFLgV3eKydwHCPnCCv+Frv8ZOBqtXk8r9DGQj/BDJrMwBk/IpvzeE0GisVu0gbtLhCnxKfIkR5AWT9nBASEwLulYHjUSxv86B0+4s9t+ph7Ydu+V7JLJ3v1j4FfdcQtPnPkcvsKA/De/MlQMwL3QagH8VYgvIKVWweeI32rpA1bHg7VqCS1cR7SlOVvsSwcP4GKPvIU5uDPGycA/ZArlEICgot704J3ACbSop1nYsWqUjxArPV5ldqV3OHxGhAO5GP6/oCShvV98+oO0sUQaMm4iqqy19by
    nextcloud-username: AgAyImEPXuevM7/VU8pUR+PCQPtZH08NJpUNzFkp/2ioFKCwVUOyxxT1HICe9Io6+gzIvM5z7nHsj8VyVUA51c4EpdUZg9NxOQboAU/RnDYOLN9JPFbUY3uLSPgATXEdyVr7nhvSbxgM644eTBXDscDrfweZTSYZ6fnSl+j52aTB2igziKyBne1oaGkaDrLLIh2eti+LrvLxbk9+c4gVVKmXfljZ6Mx6YZxmfjr7I1IlYh/roTNbPcKpA9cDFq600yIygKnMk8O2+OZHNaOM+wpvRpwN+zHlwVo08qxpN06DIOhqfcFLSiZU36hSAbAMmtOM6hFRNZBoOMVnR1Nx01jZocY948u6DqMiZZTyg8vPr8iwdLIkeA8Y0VScAytmpns4JwNEY1cP4q1eOu5kstG/vlBotWUKRF3dl9wstAubIgDnelAA1mJVs/yCXBBBaCYm/ZQlAbuyOiAZGXlbXFuOlNQn5Ju0Adob7gAX2VBsk8o/hQttsdpjrWjLz4ozx0/inutugarB8kDBrVuyPjKD7cWyzwi0jOF/u0swXDMA0Zt3A5dNCq2pA1W6TVI97tZayE7pcg1eKRqJfApqEK2rFOrtkuATQPHAWaLWwSMY16EgvveiQU1v6W2mfqe57r56RRhJjubMG6PUnKP3P/Edw1wfyFAUQsWnHS087/L6Os6u6prArxiYCt7zXfMsIU3N9TOusw==
  template:
    metadata:
      name: nextcloud-admin-creds
      namespace: nextcloud
