---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-postgresql-creds
  namespace: nextcloud
spec:
  encryptedData:
    password: AgBBXwD4syFD0vvslfFhqhmU6U/x+63yojMZc6aHiNblJRYf65NqYQQFNut9hYY+daZyuIuHBNz9XSrmh54k69U/zJSGkO7RFq1IQaWOHlhzfn+it/UtYm/vMTIiSP/32YweCeqtadxqA4YwdMwJ8wNGyEeHtdI20G50jqfrvii+PTEyCMnGb4flMy+6AlY/beSIDMFuL5ps6cQs0iVzv3vvGWEDyN4tWoRfWoADqAPQIZ8K+l1Onr7hhuQXcedhkOw/N7TxAVMfTEE9wmSPA51N27g6Ta1+x0H1z69ckinTVLRLfP1rwQci+o18T+43na46nj4rMKMQAlepIuQtASPBgZ78xUXyhlGiwvtx1Ms4zwovoTNeRKGim6OSj+oZuyuLi4TJ3Wa29s4A6ryqiF0fVibn078HpBF58+teZ8o31bksi9OmgLH2GTVSBv2o6UT1e6Rypin1BtiGrqkPmJza/Yc9keib8qolQfdLEvhpQ9C/G4QFWRRcH0T8TgqDKemDBsWhw27Jvh1MQF+iqaXTQcOT0t9lOmymUkiKDtNPBtoCe6+E6ToevS4fgWvZd5MrxhEmsqGJMn74wlquBS4PeeW5TJ9pI0AAKLqYOXBIKWzJrLdEnlUFy0eGegIrLSq62kRsGElwXpJgFvP6BvHLLECSI+ZrKiH58v9HmdC1/sOvgCNQZ1/LeGB5+yhheyWVWfdGAe3jhZt4kN8vAUiDFArDN9m4M3JnojfO
    postgres-password: AgBzHKcQ9sYbMe4cLw+QtGVVMou1PYzKkOvEHhCqjjfpOGPkZi6XNMB5zQjJTVUhiAbAHaVNl9L3I+nm7EjiWbLGYtRQ+DbMfHXRxL0og8Ph0tB4QFUR7LS4SnYzCxZ6dqIYTcI6veWdciwjAiTQh7rPjMZkzduyABpiGW75u7AzOnIOR8agp8guALBf+mbedc5R6zNxHzarHlDdw2K8yCFjMedLmIvjgO/xo1RBS6D369XL3lZz9tSS7SGfiGnO+79dTP2KGj/CRChBushBZ2f0XoS/JZTd4gfENkPwofY6qaFCXyFR65WsyDFAq4YEO6KQ9v8YMvVd5nK4N7wloqLuOs4pWylFdoRm3J+nILBWLY4ccUs6ghzlgRQ8Xda7DA0SIMLEeiOJvQKSENVldjxLfmTL+U5RHIm+eSlW6VesEQkBeLycESMWkj4ztmMh5C47DMYPFDTubat6StqsqAvJ/WCNUfafKcbl6Utu6IcQn52GWYNImb13+TPErFd3SrNGo20dE6eVE/6tUuSPAHLWTw7OuiqKxFCU5sI+tE4ZhYrQ6OGPFUtE8LGD34qZf19IEKWCZEUJxXKpGhCEQAbWFuvPVa30CjUpQr9mNzNpTr31MFYAaicGDMtO5MBK92wm3lOJKlmEc5cM9kcfwV6llbTfJH1QH9ta4yYTnVG1mHDWyU3lJUm045H2yftG3mX0WdSP2RKWGfJVfNzB2lbiN0A1/+jBCiglA1yQ
  template:
    metadata:
      name: nextcloud-postgresql-creds
      namespace: nextcloud
