---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-db-creds
  namespace: nextcloud
spec:
  encryptedData:
    db-password: AgAPO7ifOUkeYut0Jt9ha21iONIg02hG/cMEhp1UpoQ8j6duG3HceYHn2O/7pgmDR/6VKFuUMtUxIF9QJ6I7HN2LSE2AZUBFZ0nq+K0lQkLeduRNZMamb1kcNwq7vLm2Za4CuH0ADk+1zFoCYO6B0Ox8e3bcOazxV9ymYVojkep42gZ1wbs9KdPKUqVyMTqn4FoSkspN6Mh55baKQLII9IXm3Wzq456nrV9i/1lyWzTEIxuEzdXyOgks8JUWGnzA8oQZqg5nIiUvnWZBgoq4Z41UoivHryHjVZ8NyTwF3FvCv5Rz2baZudxdn281dHv2OH9Od5j/mUiGbuHVgHZ+C2xO7KsNamuNuAorEzvF0QXPBPC8dZNKxC7gf0b8EJswC/5gfgMxumqOFb+4yKeFVc7S1rddb3WL6/MunKJAAx/4sIuL7QTB2csJxScbHAwbG8UZ2N4SucVd6732BtP14RLv1UkS9mdhOPrPJ1NYlyr753Wx07nud1XzP3D3FNDCltPw0rjXaJzqxNgAL4u5QEktxR8RdFa9m7wJYWhkATRBM2ZjvX6HuG7zDExdeXPjAIz5UI1wkPwEcVsijb45Tt2qIar8ima9dWgMX2tEp0a2LDuyl0CbCwjGcupTgUEv3kRBD3bvxBPc6yitF8cxVadHVrEt9eAf6yHFScCnE/KZMejJx3knKg+vQW8lpv+IFwhvY76dWb8BJfPD3iaOoMt8bqocUF6Z7YPmiIUK
    db-username: AgBUJGeQBCpwp089Fv5DQOHSdH3phr+k78OYn+27W6HnnX0EZk4G6o4sR3ZTOFcj2MTOBYnV4SSQUlhNLX2VzDfRH5ZcuC8rEblSUeR9+Z+1A5jtUbwgjC7J7qMoT3ARNn8z76VOySBNzi21GoIiVNJqjhV4wD1uZB0KfErW5iiVPuSgdR0m923npuIzi85tICn4WRMp6bwP6GYulRm9mb42WGrt4W39NlOwy01LoJB+ujArsu4usDog96H4irQWitdYD3V6BzdorJIxA+jAJY2u3FLvsH9l3Q5jukDpk+6cRAjh8PJESPtNURE5FpnUzaM/1AoDXYyDn4QuAbRA/nKWwPOOuXumMDdvCjtoQXYvOm09u4mJkdCyydIZIHQAi1ORjbT8aap0sT/bWtMBkuhWlTAK22E6bjfm03LgEwE9pGQMCF/GMcrDNvB52v7utBZup33duAFh9Kz0h7hoQqHayT07/y9N4TDe06tP3b0VgBIOevJkQIN9aGYvBOwufGdftp4ijc0ak72nDz4PPLxRw56neFPSdqDQxHtVRPT2W2TlrIEUG5/Gx4Jqt1RwtX5TrVfyhHSMgY6VllmUpFhKDBYwBvTCPo7/P8bajsas9Avxw/j3RolGRoCwPEDUuEHU0ubziNteaTnf0ZJlSPue2daDUywvYg8/MiM3XKhf2ydWE3+qU4Ja69vQOXpDUn3EO4eQlkZNGaw=
  template:
    metadata:
      name: nextcloud-db-creds
      namespace: nextcloud
