---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-admin-creds
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-password: AgAnU+6ovyUDXoAL87lR9CNCMHQ9w5mvYCYx+tCEU6tlokR0s5s2iYsHGPcTDnWmw2OnfhqmtghS3I/yf1GpqCwN0U4TfNeYeNxrC9J/oCKwFhWcGRscuLJ3oY6w4lB0qm16bSRwEJOVXBo8YWJMelVuUUi8pjhMj1jpzry3PS7lXKmHPWdodVGAMDygXbYjKc4kWvxVCdvbeeJgNCvYmBxwy2DlSRX04xNGYnmdJHOzgz3SYLnhXxKd6sRzSFC9KgetewaIlVHpVzc8e0/IiqKBX1uzwo3q7eTlkYiKGoeeu6RJbqN/BeLhSy1vxKgG8uhUEZmfjabD7rKtvC2PS7n3IeHyEHJMxUh43+R+nV6TMCfAuZggc9P+IgwIX7haX4csKfv8U/lpKeaGSJKVQ4cUDpHZuUzIROZNEMz/rNVUJo2jp0rB3L3T4rgaBF26WCOeeURWgpsua5axXO5Q/M3EvL/vNILtnIxGJhvCtEn4XUSSZ2HV6YLGEdJqLWas7q5F8Av0zjB2syVf0eRnlIxGsvh6EnJoVECj7dFKpa5iyXkpu1ucHbsq56g21/pU9hskARrPeiZK3KNzhN+rZ3P6AUiIVjCl/vgsBrnHOnuuTLDLLqLa7fCvOvSpBXxpRKr1y9IBbPcfiX6Jss72It+iuS3B8JurABF+EHBV0kezGTPRecNax25tcNpmJCTBXtryn4mhWuRwZQ==
    nextcloud-username: AgBSu0vdxxcKftqKDRI9LN4JSJknpb5VInJ/bZylatQKVx0SyR/OteF/SbWz73kfCu0Dk0YXHNqPIHiDNKePk2RaE3z5LlKcgCAXY3I4quLIel3VMBzg8aZv9cfZPrK8nS6FWmbOkS2DQqg/a739q3CT4wy1XYJZKEpmuesZF2Z7ZGJ6l7Zz7S9fCnhz8UhAtBrkNjRqUecYQc1B3GiHRpw/1BZw3cLIMDJNqNZC8kkYT0CdxS+5QDHHGSTlHO2QzzW1IgelnwuopdMSU2GNUA+ypNfjL93Ezom8hY5jFF7fsI9fv31/DJVgNF7FxJAxwIZWuH9OpI8etu4af3qPSCKMh1HPIGZOtKoos8mYSeTqYRkWnx41scgr7SIwkewo+yGO/sAk/a1SPMVWeADgIWiaynvxsFPWFyFalepLmO+ZOt2ASZqa9zttrluyNvqC7u9wRoAtQ8K/+I5SlayE9bkkPCGMuhlxnwWoEwoQMX0teaJPKBd+Utug8QX3Q1JqZnVYpXAh2iyQEjxUSv40TpTe7XTK0mhMovyRf7OP3F4nqPoBWkAgm8Jf3gQtueqSEAkCNsLK27CrzE0aH7W2Qit82UjW5YiJdMA9j0miAInXntelhn1gA9QMRMlCZDExjPG3Uo6cIbW1TYqHz7blpb9kELOg5/cIC+GEbdfCv4REeOGAXdiHR5QnOib+kNdb380ayRJfxg==
  template:
    metadata:
      name: nextcloud-admin-creds
      namespace: nextcloud
