---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-postgresql-creds
  namespace: paperless
spec:
  encryptedData:
    postgres-password: AgByxGnqZLXaUiSVi45FTZjXCiUMWvTVzUpSot65ZaVyATZa7g2sg7XPVjDM6bpeYIwgx1aTCvWvq3cP9hEhoaoc12mYPH6eRGJSy7UFHR3gXAIaAPTlhGjIzWoeVCVDMGNSihIRGD/4f7GOY+NbT6iu3rJg7Y6Uztyn4XMH4lU20dQ51Yf41WLYg2yY8JRDgTAm9peZbI3WKaqdw4CHcRA/h+wE+lqej/m2tMU115A8bB5M1K0ktaBos++qWjBDiANLymrGD92p/OdaCtTppjkzeyJZJlDqhl6S3TnZS2PA6FIKH5oW3OAe78Ppdk341uC7i62lgSiffbj0qnY2FQL/5gPnXuyrXSXeXeLY3OprvBPPtYTj7gQLSZlRkxCKRCM+k1/hj+T0MzIsHKfHi5pF5xeKhSs6oi6dzI+ittxG9zE551vXXTHze0G0TNtF+GPVb/G3skAhotZtdRRWy9fc4l/C8+37/OBAkXOoxkd8FeN4laQhaic2IppcEaQbixoBNqquvOszyDqCmPYiPNcg2T5Cdi8yUdErz6jnUVfStGLTp+7/vZjNzHPgE9Nt1DhDf04GFFqabV5P6Aq+CFZJZBTClcKAoEqEKUk4V7WphYikAZTQDvHcHv6sOOIfZiN73HnGQGQTJY9AOo5xAxfwiOKU1Qcw09ifozlDs3rfgj+OO8rU1m6qrwmuOijcLnTYV7byYoDoYk+E7Xndt88tbNp0wMmHZGElXWxZ
  template:
    metadata:
      name: paperless-postgresql-creds
      namespace: paperless
